### ISSUE TITLE
current code is missing model/readers.rb

### ISSUE THREAD

**Issue by truedat101** [IoTone/ProjectGyr#22]
Missing file.  Needs to be checked in:

```
oranji:ProjectGyruss-vscode.git dkords$ ruby gyr_reader_tier.rb
Traceback (most recent call last):
	5: from gyr_reader_tier.rb:9:in `<main>'
	4: from /Users/dkords/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/dkords/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Users/dkords/dev/projects/iotone/ProjectGyruss-vscode.git/models/mongo_db.rb:6:in `<top (required)>'
	1: from /Users/dkords/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/dkords/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ./models/readers.rb
```

**Comment by truedat101** [comment]
@davicitoafc can you check in the missing file?

**Comment by truedat101** [comment]
Checked in on 88474a4d58f37fe8132be43e91c8e1cf4b9e9e48.
